# Generated by Django 3.1 on 2023-10-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20231011_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='yesha',
        ),
    ]
